// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `core_slot`, `initialize`

/// The narrow JSON boundary used by Flutter. Core access is cloned while the
/// singleton lock is held; no network or storage operation awaits under it.
Future<String> call({required String request}) =>
    RustLib.instance.api.crateApiCall(request: request);
