include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/src/rust/**
    - build/**
    - android/**
    - ios/**
    - windows/**
    - macos/**
    - linux/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    avoid_print: true
    always_declare_return_types: true
    directives_ordering: true
    prefer_const_constructors: true
    use_build_context_synchronously: true
